name: Deploy

on:
  pull_request:
    branches: main
    types: [closed]

jobs:
  deploy-web:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: echo "User name - ${{ secrets.USER_NAME }}"
