name: Deploy

on:
  pull_request:
    branches: main
    types: [closed]

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - run: echo "User name: ${{ secrets.USER_NAME }}"
